import { css } from "styled-system/css";

export const briefStyles = {
  briefLayout: css({ maxW: "1050px", mx: "auto", display: "grid", gap: { base: "7", md: "9" } }),
  planSummary: css({
    display: "grid",
    gap: { base: "5", md: "6" },
    maxW: "880px",
    pt: { base: "2", md: "4" },
  }),
  planLead: css({
    display: "grid",
    gap: "3",
  }),
  planKicker: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "2",
    width: "fit-content",
    color: "brand.green",
    fontSize: "sm",
    fontWeight: "800",
  }),
  planExperiment: css({
    display: "grid",
    gap: "2",
    maxW: "72ch",
    pt: "5",
    borderTopWidth: "1px",
    borderColor: "brand.border",
  }),
  planLabel: css({
    color: "brand.green",
    fontSize: "sm",
    fontWeight: "800",
  }),
  planStartReason: css({ maxW: "72ch", color: "brand.muted", lineHeight: "1.6" }),
  planDisclosure: css({
    maxW: "72ch",
    color: "brand.muted",
    fontSize: "xs",
    lineHeight: "1.5",
  }),
  briefWorkbench: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", lg: "minmax(240px, 0.8fr) minmax(0, 1.7fr)" },
    gap: { base: "4", lg: "5" },
    alignItems: "start",
  }),
  briefPicker: css({
    display: "grid",
    alignContent: "start",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "6px 2px 6px 6px",
    overflow: { base: "hidden", lg: "auto" },
    position: { lg: "sticky" },
    top: { lg: "20" },
    maxH: { lg: "calc(100dvh - 96px)" },
  }),
  briefPickerItem: css({
    width: "full",
    display: "grid",
    gridTemplateColumns: "28px minmax(0, 1fr) 18px",
    alignItems: "center",
    gap: "3",
    p: "4",
    color: "brand.ink",
    textAlign: "left",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
    cursor: "pointer",
    _hover: { bg: "brand.sage" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "-2px" },
  }),
  briefPickerItemActive: css({
    bg: "brand.signal",
    color: "brand.ink",
    "& > span:first-child": { bg: "brand.green", color: "white" },
  }),
  briefPickerNumber: css({
    width: "7",
    height: "7",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "full",
    bg: "brand.ink",
    color: "brand.panel",
    fontSize: "xs",
    fontWeight: "800",
  }),
  briefPickerTitle: css({ display: "block", fontWeight: "800", lineHeight: "1.25" }),
  briefPickerStep: css({
    display: { base: "none", md: "block" },
    mt: "1",
    color: "brand.muted",
    fontSize: "xs",
    lineHeight: "1.45",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  briefDetail: css({
    minW: "0",
    p: { base: "5", md: "6" },
    display: "grid",
    alignContent: "start",
    gap: "5",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "6px 2px 6px 6px",
    boxShadow: "2px 3px 0 rgba(21, 24, 39, 0.07)",
  }),
  briefDetailGrid: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))" },
    gap: "5",
    py: "4",
    borderTopWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  itemStart: css({ p: "4", bg: "brand.sageStrong", color: "brand.ink", borderRadius: "l2" }),
  itemPrompt: css({
    display: "grid",
    gap: "3",
    pt: "1",
  }),
  briefSafety: css({
    display: "flex",
    alignItems: "start",
    gap: "2",
    p: "3",
    bg: "brand.amber",
    color: "brand.amberInk",
    borderRadius: "l2",
    fontSize: "sm",
  }),
  prompt: css({
    maxW: "75ch",
    fontFamily: "inherit",
    fontSize: "md",
    lineHeight: "1.7",
    p: { base: "4", md: "5" },
    bg: "brand.sage",
    borderRadius: "l2",
    borderWidth: "1px",
    borderColor: "brand.border",
  }),
  promptParagraph: css({
    whiteSpace: "pre-line",
    "&:not(:last-child)": { mb: "4" },
  }),
  promptLead: css({ fontWeight: "650", color: "brand.ink" }),
  promptLabel: css({ display: "block", mb: "1", color: "brand.ink", fontWeight: "800" }),
  downloadLink: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    minH: "10",
    px: "4",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "l2",
    bg: "brand.panel",
    fontWeight: "semibold",
    _hover: { borderColor: "brand.green", bg: "brand.sage" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" },
  }),
};
