import { css } from "styled-system/css";

export const briefStyles = {
  briefLayout: css({ maxW: "1050px", mx: "auto", display: "grid", gap: "5" }),
  planSummary: css({
    display: "grid",
    gap: "5",
    p: { base: "5", md: "7" },
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.green",
    borderRadius: "6px 2px 6px 6px",
    boxShadow: "4px 5px 0 var(--colors-brand-green)",
  }),
  planStart: css({
    display: "flex",
    alignItems: "start",
    gap: "3",
    p: "4",
    bg: "brand.ink",
    borderRadius: "l2",
    color: "white",
  }),
  planCopy: css({ maxW: "75ch" }),
  planStartIcon: css({
    boxSize: "9",
    flexShrink: "0",
    display: "grid",
    placeItems: "center",
    bg: "brand.signal",
    color: "brand.ink",
    borderRadius: "3px 9px 3px 3px",
  }),
  planStartReason: css({ color: "#c7ccda", lineHeight: "1.6" }),
  briefWorkbench: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", lg: "minmax(240px, 0.8fr) minmax(0, 1.7fr)" },
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "6px 2px 6px 6px",
    overflow: "hidden",
    bg: "brand.panel",
    boxShadow: "2px 3px 0 rgba(21, 24, 39, 0.07)",
  }),
  briefPicker: css({
    display: "grid",
    alignContent: "start",
    bg: "brand.panel",
    borderBottomWidth: { base: "1px", lg: "0" },
    borderRightWidth: { base: "0", lg: "1px" },
    borderColor: "brand.border",
  }),
  briefPickerItem: css({
    width: "full",
    display: "grid",
    gridTemplateColumns: "28px minmax(0, 1fr) 18px",
    alignItems: "center",
    gap: "3",
    p: "4",
    color: "brand.ink",
    textAlign: "left",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
    cursor: "pointer",
    _hover: { bg: "brand.sage" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "-2px" },
  }),
  briefPickerItemActive: css({
    bg: "brand.signal",
    color: "brand.ink",
    "& > span:first-child": { bg: "brand.green", color: "white" },
  }),
  briefPickerNumber: css({
    width: "7",
    height: "7",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "full",
    bg: "brand.ink",
    color: "brand.panel",
    fontSize: "xs",
    fontWeight: "800",
  }),
  briefPickerTitle: css({ display: "block", fontWeight: "800", lineHeight: "1.25" }),
  briefPickerStep: css({
    display: { base: "none", md: "block" },
    mt: "1",
    color: "brand.muted",
    fontSize: "xs",
    lineHeight: "1.45",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  briefDetail: css({
    minW: "0",
    p: { base: "5", md: "6" },
    display: "grid",
    alignContent: "start",
    gap: "5",
  }),
  briefDetailGrid: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))" },
    gap: "5",
    py: "4",
    borderTopWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  itemStart: css({ p: "4", bg: "brand.sageStrong", color: "brand.ink", borderRadius: "l2" }),
  briefSafety: css({
    display: "flex",
    alignItems: "start",
    gap: "2",
    p: "3",
    bg: "brand.amber",
    color: "brand.amberInk",
    borderRadius: "l2",
    fontSize: "sm",
  }),
  prompt: css({
    maxW: "75ch",
    fontFamily: "inherit",
    fontSize: "md",
    lineHeight: "1.7",
    p: { base: "4", md: "5" },
    bg: "brand.sage",
    borderRadius: "l2",
    borderWidth: "1px",
    borderColor: "brand.border",
    maxH: "520px",
    overflowY: "auto",
  }),
  promptParagraph: css({
    whiteSpace: "pre-line",
    "&:not(:last-child)": { mb: "4" },
  }),
  promptLead: css({ fontWeight: "650", color: "brand.ink" }),
  promptLabel: css({ display: "block", mb: "1", color: "brand.ink", fontWeight: "800" }),
  downloadLink: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "2",
    minH: "10",
    px: "4",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "l2",
    bg: "brand.panel",
    fontWeight: "semibold",
    _hover: { borderColor: "brand.green", bg: "brand.sage" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" },
  }),
};
