import { css } from "styled-system/css";

export const flowStyles = {
  reviewHeader: css({ display: "grid", gap: "2", maxW: "760px" }),
  reviewTitle: css({ fontSize: { base: "4xl", md: "5xl" }, fontWeight: "850", letterSpacing: "-0.035em", lineHeight: "1.02", textWrap: "balance" }),
  reviewIntro: css({ color: "brand.muted", fontSize: { base: "md", md: "lg" }, lineHeight: "1.6", maxW: "68ch" }),
  profileSummary: css({
    display: "grid",
    gap: "3",
    py: { base: "5", md: "6" },
    px: { base: "4", md: "6" },
    bg: "brand.panel",
    borderTopWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.ink",
  }),
  profileSummaryLabel: css({ color: "brand.green", fontSize: "sm", fontWeight: "850" }),
  profileSummaryText: css({ maxW: "72ch", fontSize: { base: "lg", md: "xl" }, lineHeight: "1.55", color: "brand.ink" }),
  reviewPrimaryActions: css({ mt: "2", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "3", flexWrap: "wrap" }),
  refineCue: css({
    justifySelf: "center",
    display: "grid",
    justifyItems: "center",
    gap: "1",
    color: "brand.green",
    fontWeight: "850",
    textAlign: "center",
    _hover: { color: "brand.ink", transform: "translateY(1px)" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "4px" },
    "& small": { color: "brand.muted", fontSize: "xs", fontWeight: "600" },
  }),
  directionHeader: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "minmax(0, 1fr) auto" },
    alignItems: "start",
    gap: { base: "3", md: "4" },
    mb: "4",
  }),
  directionControls: css({
    display: "flex",
    alignItems: "center",
    justifyContent: { base: "flex-start", md: "flex-end" },
    gap: "2",
    flexWrap: "wrap",
  }),
  directionCount: css({ px: "2.5", py: "1", bg: "brand.signal", borderWidth: "1px", borderColor: "brand.ink", borderRadius: "3px", fontSize: "xs", fontWeight: "850" }),
  directionGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))", xl: "repeat(3, minmax(0, 1fr))" }, gap: "2" }),
  directionChoice: css({
    position: "relative",
    width: "full",
    h: "36",
    overflow: "hidden",
    display: "grid",
    gridTemplateColumns: "24px minmax(0, 1fr)",
    alignContent: "start",
    gap: "3",
    p: "3",
    textAlign: "left",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "4px 1px 4px 4px",
    cursor: "pointer",
    transition: "common",
    _hover: { borderColor: "brand.green", transform: "translateY(-1px)" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" },
  }),
  directionChoiceSelected: css({
    position: "relative",
    width: "full",
    h: "36",
    overflow: "hidden",
    display: "grid",
    gridTemplateColumns: "24px minmax(0, 1fr)",
    alignContent: "start",
    gap: "3",
    p: "3",
    textAlign: "left",
    bg: "brand.amber",
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "4px 1px 4px 4px",
    boxShadow: "2px 2px 0 token(colors.brand.ink)",
    transform: "translate(-1px, -1px)",
    cursor: "pointer",
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "3px" },
  }),
  directionChoiceMark: css({ mt: "0.5", boxSize: "5", display: "grid", placeItems: "center", borderWidth: "1px", borderColor: "brand.ink", borderRadius: "3px", bg: "brand.panel", color: "brand.ink" }),
  directionChoiceCopy: css({
    display: "grid",
    gap: "1.5",
    minW: "0",
    overflow: "hidden",
    "& strong": { minH: "10", fontSize: "md", fontWeight: "850", lineHeight: "1.25", lineClamp: 2 },
    "& > span": { color: "brand.muted", fontSize: "sm", lineHeight: "1.4", lineClamp: 2 },
  }),
  directionContinue: css({
    display: "flex",
    justifyContent: "flex-end",
    mt: "4",
    "& > button": { width: { base: "full", md: "auto" } },
  }),
  profileEvidence: css({ display: "grid", gap: "4", py: "6", borderTopWidth: "1px", borderBottomWidth: "1px", borderColor: "brand.border" }),
  evidenceHeader: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "auto minmax(0, 1fr)" }, alignItems: "baseline", gap: { base: "1", md: "4" } }),
  evidenceGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))" }, gap: "4" }),
  evidenceFacts: css({
    p: "4",
    bg: "brand.sage",
    borderRadius: "2px",
    "& ul": { mt: "3", display: "grid", gap: "2", ps: "5", listStyleType: "disc" },
    "& li": { color: "brand.ink", fontSize: "sm", lineHeight: "1.5" },
  }),
  evidenceInferences: css({
    p: "4",
    bg: "brand.amber",
    borderRadius: "2px",
    "& ul": { mt: "3", display: "grid", gap: "2", ps: "5", listStyleType: "disc" },
    "& li": { color: "brand.amberInk", fontSize: "sm", lineHeight: "1.5" },
  }),
  evidenceLabel: css({ display: "flex", alignItems: "center", gap: "2", fontWeight: "850" }),
  profileEdit: css({ pt: "2", maxW: "760px" }),
  reviewFooter: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "3",
    flexWrap: "wrap",
    p: "3",
    bg: "brand.ink",
    color: "white",
    borderRadius: "6px 2px 6px 6px",
    boxShadow: "5px 5px 0 token(colors.brand.signal)",
    "& > span": { color: "#c7ccda", fontSize: "sm" },
  }),
  briefDisclosure: css({ maxW: "72ch", p: "3", bg: "brand.sage", color: "brand.muted", borderWidth: "1px", borderColor: "brand.border", borderRadius: "4px", fontSize: "sm", lineHeight: "1.5" }),
  nextStepSection: css({ display: "grid", gap: "4", pt: "3" }),
  nextStepGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))" }, gap: "4" }),
  nextStepSelfServe: css({
    display: "grid",
    alignContent: "start",
    gap: "3",
    p: "5",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "6px 2px 6px 6px",
    boxShadow: "2px 3px 0 rgba(21, 24, 39, 0.07)",
    "& button": { mt: "auto" },
  }),
  nextStepHelp: css({
    display: "grid",
    alignContent: "start",
    gap: "3",
    p: "5",
    bg: "brand.ink",
    color: "white",
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "6px 2px 6px 6px",
    boxShadow: "6px 6px 0 token(colors.brand.signal), 0 18px 40px rgba(21, 24, 39, 0.16)",
    "& p": { color: "#c7ccda", lineHeight: "1.55" },
  }),
  nextStepIcon: css({ boxSize: "10", display: "grid", placeItems: "center", bg: "brand.signal", color: "brand.ink", borderRadius: "3px 9px 3px 3px" }),
  helpLink: css({ mt: "auto", minH: "11", display: "inline-flex", alignItems: "center", justifyContent: "center", gap: "2", px: "4", bg: "brand.signal", color: "brand.ink", borderRadius: "4px", fontWeight: "850", _hover: { transform: "translateY(-1px)", boxShadow: "0 3px 0 rgba(255, 255, 255, 0.24)" }, _focusVisible: { outline: "2px solid white", outlineOffset: "2px" } }),
  generationPage: css({ minH: "calc(100dvh - 64px)", display: "grid", placeItems: "center", px: "5", py: "10" }),
  generationPanel: css({
    width: "full",
    maxW: "760px",
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "72px minmax(0, 1fr)" },
    gap: { base: "5", md: "6" },
    p: { base: "6", md: "9" },
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "10px 2px 10px 10px",
    boxShadow: "8px 8px 0 token(colors.brand.green), 0 22px 60px rgba(21, 24, 39, 0.12)",
  }),
  generationMark: css({ boxSize: "16", display: "grid", placeItems: "center", bg: "brand.signal", color: "brand.ink", borderWidth: "1px", borderColor: "brand.ink", borderRadius: "5px 14px 5px 5px", boxShadow: "3px 3px 0 token(colors.brand.ink)" }),
  generationKicker: css({ color: "brand.green", fontSize: "sm", fontWeight: "850" }),
  generationTitle: css({ mt: "2", maxW: "620px", fontSize: { base: "3xl", md: "5xl" }, fontWeight: "850", letterSpacing: "-0.035em", lineHeight: "1.02", textWrap: "balance" }),
  generationCopy: css({ mt: "4", maxW: "65ch", color: "brand.muted", fontSize: { base: "md", md: "lg" }, lineHeight: "1.6" }),
  generationSteps: css({ gridColumn: { md: "2" }, display: "grid", gap: "2", pt: "1" }),
  generationStep: css({ display: "grid", gridTemplateColumns: "24px minmax(0, 1fr)", alignItems: "center", gap: "2", color: "brand.muted", fontSize: "sm", "&:first-child": { color: "brand.ink", fontWeight: "800" }, "& > span:first-child": { color: "brand.green" } }),
  generationSpinner: css({ animation: "spin 900ms linear infinite" }),
  generationSkeleton: css({ gridColumn: { md: "2" }, display: "grid", gap: "2", pt: "2", "& span": { display: "block", h: "3", bg: "brand.sageStrong", borderRadius: "2px", animation: "pulse 1.6s ease-in-out infinite" }, "& span:nth-child(1)": { width: "92%" }, "& span:nth-child(2)": { width: "76%" }, "& span:nth-child(3)": { width: "84%" } }),
};
