import { css } from "styled-system/css";

export const generationDialogStyles = {
  gridIntroActions: css({
    display: "flex",
    alignItems: { base: "stretch", sm: "center" },
    justifyContent: { base: "space-between", lg: "flex-end" },
    flexDirection: { base: "column-reverse", sm: "row" },
    gap: "2",
    gridColumn: { lg: "3" },
  }),
  generationAction: css({
    minH: "11",
    px: "4",
    boxShadow: "3px 3px 0 token(colors.brand.ink)",
    "&:active": { transform: "translate(2px, 2px)", boxShadow: "1px 1px 0 token(colors.brand.ink)" },
  }),
  historyNav: css({
    display: "flex",
    alignItems: "center",
    gap: "1",
    minH: "10",
    px: "1",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "4px",
  }),
  historyButton: css({
    boxSize: "8",
    display: "grid",
    placeItems: "center",
    borderRadius: "3px",
    color: "brand.ink",
    cursor: "pointer",
    _hover: { bg: "brand.sageStrong", color: "brand.green" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "1px" },
    _disabled: { color: "brand.muted", cursor: "not-allowed", opacity: "0.45" },
  }),
  historyCount: css({
    minW: "72px",
    textAlign: "center",
    color: "brand.muted",
    fontSize: "xs",
    fontWeight: "800",
    fontVariantNumeric: "tabular-nums",
  }),
  generationDialog: css({
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "10px 2px 10px 10px",
    boxShadow: "8px 8px 0 token(colors.brand.green), 0 28px 80px rgba(21, 24, 39, 0.24)",
    "& .dialog__header": {
      px: { base: "5", md: "7" },
      pt: { base: "5", md: "6" },
      pb: "3",
      borderBottomWidth: "1px",
      borderColor: "brand.border",
    },
    "& .dialog__title": {
      maxW: "680px",
      fontSize: { base: "2xl", md: "4xl" },
      fontWeight: "850",
      letterSpacing: "-0.035em",
      lineHeight: "1.04",
    },
    "& .dialog__description": {
      mt: "2",
      maxW: "68ch",
      color: "brand.muted",
      lineHeight: "1.55",
    },
    "& .dialog__body": { px: { base: "5", md: "7" }, py: { base: "4", md: "5" } },
    "& .dialog__footer": {
      px: { base: "5", md: "7" },
      py: "4",
      borderTopWidth: "1px",
      borderColor: "brand.border",
      bg: "#f7f8ff",
    },
  }),
  generationForm: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "minmax(0, 1.7fr) minmax(240px, 0.8fr)" },
    gap: { base: "4", md: "5" },
    alignItems: "stretch",
  }),
  generationDialogError: css({
    gridColumn: { md: "1 / -1" },
    p: "3",
    bg: "red.subtle.bg",
    color: "red.subtle.fg",
    borderRadius: "4px",
    fontSize: "sm",
    lineHeight: "1.45",
  }),
  questionList: css({ display: "grid", gap: "2" }),
  questionBlock: css({ display: "grid", gap: "1" }),
  questionLabel: css({
    display: "grid",
    gridTemplateColumns: "28px minmax(0, 1fr)",
    alignItems: "start",
    gap: "2",
    fontSize: "md",
    fontWeight: "semibold",
    lineHeight: "1.4",
  }),
  questionNumber: css({
    boxSize: "7",
    display: "grid",
    placeItems: "center",
    bg: "brand.signal",
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "3px 8px 3px 3px",
    fontSize: "xs",
    fontWeight: "900",
  }),
  choiceGrid: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", md: "repeat(3, minmax(0, 1fr))" },
    gap: "2",
    ps: { md: "9" },
  }),
  generationOption: css({
    minH: "9",
    px: "3",
    py: "2",
    display: "flex",
    alignItems: "center",
    textAlign: "left",
    bg: "brand.panel",
    color: "brand.ink",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "4px 1px 4px 4px",
    fontSize: "sm",
    fontWeight: "normal",
    lineHeight: "1.4",
    cursor: "pointer",
    transition: "common",
    _hover: { borderColor: "brand.green", bg: "brand.sage" },
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" },
  }),
  generationOptionSelected: css({
    minH: "9",
    px: "3",
    py: "2",
    display: "flex",
    alignItems: "center",
    textAlign: "left",
    bg: "brand.signal",
    color: "brand.ink",
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "4px 1px 4px 4px",
    boxShadow: "2px 2px 0 token(colors.brand.ink)",
    fontSize: "sm",
    fontWeight: "medium",
    lineHeight: "1.4",
    cursor: "pointer",
    transform: "translate(-1px, -1px)",
    _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "3px" },
  }),
  feedbackBlock: css({
    display: "grid",
    alignContent: "start",
    gap: "2",
    pt: { base: "3", md: "0" },
    ps: { md: "5" },
    borderTopWidth: { base: "1px", md: "0" },
    borderLeftWidth: { md: "1px" },
    borderColor: "brand.border",
  }),
  feedbackLabel: css({ fontSize: "lg", fontWeight: "850" }),
  feedbackHint: css({ color: "brand.muted", fontSize: "sm", lineHeight: "1.5" }),
  feedbackInput: css({
    minH: { base: "22", md: "44" },
    resize: "vertical",
    bg: "brand.panel",
    borderColor: "brand.ink",
    borderRadius: "5px 1px 5px 5px",
    _focus: { borderColor: "brand.green", boxShadow: "0 0 0 2px token(colors.brand.sageStrong)" },
  }),
  dialogFooter: css({
    width: "full",
    display: "flex",
    alignItems: { base: "stretch", sm: "center" },
    justifyContent: "space-between",
    flexDirection: { base: "column", sm: "row" },
    gap: "3",
  }),
  dialogFooterNote: css({ color: "brand.muted", fontSize: "xs", lineHeight: "1.4" }),
};
