import { css } from "styled-system/css";

export const landingDropStyles = {
  pageDropOverlay: css({
    position: "fixed",
    inset: "0",
    zIndex: "modal",
    p: { base: "3", md: "6" },
    bg: "brand.green",
    color: "white",
    animationName: "fade-in",
    animationDuration: "fast",
    animationTimingFunction: "ease-out",
    _motionReduce: { animation: "none" },
  }),
  pageDropOverlayInner: css({
    width: "full",
    height: "full",
    maxW: "1500px",
    mx: "auto",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: "6",
    p: { base: "5", md: "10" },
    borderWidth: { base: "2px", md: "3px" },
    borderColor: "brand.ink",
    borderRadius: "10px 2px 10px 10px",
    boxShadow: "10px 10px 0 token(colors.brand.ink), 0 28px 80px rgba(21, 24, 39, 0.28)",
    overflow: "hidden",
  }),
  pageDropOverlayTop: css({
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    gap: "6",
  }),
  pageDropKicker: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "2.5",
    px: "3",
    py: "2",
    bg: "brand.signal",
    color: "brand.ink",
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "4px 10px 4px 4px",
    boxShadow: "3px 3px 0 token(colors.brand.ink)",
    fontSize: { base: "sm", md: "md" },
    fontWeight: "850",
  }),
  pageDropGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: { base: "1", md: "1.5" },
    width: { base: "16", md: "24" },
    aspectRatio: "1",
    p: { base: "1.5", md: "2" },
    bg: "brand.ink",
    borderRadius: "5px 14px 5px 5px",
    "& span": {
      bg: "brand.green",
      borderWidth: "1px",
      borderColor: "white",
      borderRadius: "1px",
    },
    "& span:nth-child(5)": {
      bg: "brand.signal",
      borderColor: "brand.signal",
    },
  }),
  pageDropMessage: css({
    alignSelf: "center",
    animationName: "slide-from-bottom, fade-in",
    animationDuration: "normal",
    animationTimingFunction: "ease-out",
    _motionReduce: { animation: "none" },
  }),
  pageDropTitle: css({
    display: "grid",
    maxW: "1100px",
    fontSize: { base: "5xl", sm: "6xl", md: "8xl" },
    fontWeight: "900",
    lineHeight: "0.82",
    letterSpacing: "-0.04em",
    textTransform: "uppercase",
    "& span:first-child": { color: "white" },
    "& span:last-child": {
      color: "brand.signal",
      textShadow: "5px 5px 0 token(colors.brand.ink)",
    },
  }),
  pageDropCopy: css({
    mt: { base: "6", md: "8" },
    color: "white",
    fontSize: { base: "lg", md: "2xl" },
    fontWeight: "800",
  }),
  pageDropFooter: css({
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "2",
    color: "white",
    fontSize: { base: "sm", md: "md" },
    fontWeight: "800",
    "& span": {
      px: "3",
      py: "2",
      borderWidth: "1px",
      borderColor: "rgba(255, 255, 255, 0.7)",
      borderRadius: "3px",
    },
  }),
};
