import { css } from "styled-system/css";
import { briefStyles } from "./brief-styles";
import { flowStyles } from "./flow-styles";
import { generationDialogStyles } from "./generation-dialog-styles";
import { landingDropStyles } from "./landing-drop-styles";

/*
THESIS: A strategy board, not another cream AI landing page.
OWN-WORLD: Cool paper, structural ink, electric periwinkle, citrus signal, crisp offset edges.
STORY: Understand the map, scan the opportunity space, select a signal, leave with a next move.
FIRST VIEWPORT: Compact dark app bar over a split promise/intake composition; the working 3×3 proof board follows directly below.
FORM: Operate-mode strategy studio; grounded direction three; seed 2bf2385d.
*/
export const styles = {
  ...briefStyles,
  ...flowStyles,
  ...generationDialogStyles,
  ...landingDropStyles,
  app: css({ minH: "100dvh", bg: "brand.canvas", color: "brand.ink" }),
  header: css({
    h: "16",
    px: { base: "3", md: "6" },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: { base: "2", md: "4" },
    borderBottomWidth: "1px",
    borderColor: "brand.ink",
    bg: "brand.ink",
    color: "white",
    position: "sticky",
    top: "0",
    zIndex: "sticky",
  }),
  brand: css({ display: "flex", alignItems: "center", gap: "3", minW: "0" }),
  brandHomeLink: css({
    display: "flex",
    alignItems: "center",
    gap: "3",
    color: "inherit",
    textDecoration: "none",
    borderRadius: "6px",
    flexShrink: "0",
    _focusVisible: { outline: "2px solid token(colors.brand.signal)", outlineOffset: "3px" },
  }),
  brandMark: css({
    boxSize: "9",
    borderRadius: "4px 10px 4px 4px",
    display: "grid",
    placeItems: "center",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "#3a3f52",
    p: "1",
    flexShrink: "0",
  }),
  brandMarkImage: css({ display: "block", width: "full", height: "full" }),
  brandName: css({
    display: { base: "none", sm: "inline" },
    fontSize: { base: "lg", md: "xl" },
    fontWeight: "800",
    letterSpacing: "tight",
    whiteSpace: "nowrap",
  }),
  headerContext: css({
    display: { base: "none", xl: "block" },
    color: "#b8bfd2",
    borderLeftWidth: "1px",
    borderColor: "#3a3f52",
    ps: "4",
    ms: "1",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  }),
  headerStats: css({
    display: { base: "none", lg: "flex" },
    alignItems: "start",
    gap: "3",
    color: "#b8bfd2",
    fontSize: "sm",
    minW: "0",
    whiteSpace: "nowrap",
  }),
  headerStatStrong: css({ display: "inline-flex", alignItems: "center", gap: "1.5", color: "white", fontWeight: "semibold" }),
  headerNotice: css({
    display: { base: "none", "2xl": "inline" },
    maxW: "240px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    color: "brand.signal",
  }),
  headerActions: css({ display: "flex", alignItems: "center", justifyContent: "flex-end", gap: "2", flexShrink: "0", ms: "auto" }),
  headerSecondaryAction: css({
    borderColor: "#656b80",
    color: "#e3e6ef",
    boxShadow: "none",
    _hover: { bg: "#262a3a", borderColor: "#8b91a5", color: "white" },
    _focusVisible: { outlineColor: "brand.signal" },
  }),
  headerMobileLabel: css({ display: { base: "inline", md: "none" } }),
  headerDesktopLabel: css({ display: { base: "none", md: "inline" } }),
  page: css({ maxW: "1600px", mx: "auto", px: { base: "4", md: "8" }, py: { base: "6", md: "8" } }),
  gridPage: css({ py: { base: "4", md: "4" } }),
  gridIntro: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", lg: "auto minmax(0, 1fr) auto" },
    alignItems: { lg: "end" },
    gap: { base: "2", lg: "8" },
    mb: "4",
  }),
  gridTitle: css({
    mt: "1",
    fontSize: { base: "3xl", md: "4xl" },
    fontWeight: "800",
    lineHeight: "1.05",
    whiteSpace: { lg: "nowrap" },
  }),
  gridIntroCopy: css({ color: "brand.muted", fontSize: { base: "sm", md: "md" }, lineHeight: "1.5", pb: { lg: "1" }, maxW: "3xl" }),
  landing: css({
    minH: "calc(100dvh - 64px)",
    maxW: "1500px",
    mx: "auto",
    px: { base: "5", md: "10" },
    py: { base: "8", lg: "12" },
  }),
  landingHero: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", lg: "minmax(0, 1.12fr) minmax(440px, 0.88fr)" },
    columnGap: { lg: "16" },
    rowGap: { base: "10", lg: "0" },
    alignItems: "center",
  }),
  heroContent: css({
    maxW: "720px",
    py: { lg: "8" },
    gridColumn: { lg: "1" },
    gridRow: { lg: "1" },
  }),
  eyebrow: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "2",
    color: "brand.ink",
    fontSize: "sm",
    fontWeight: "700",
  }),
  eyebrowDot: css({ boxSize: "2.5", bg: "brand.signal", borderRadius: "2px 5px 2px 2px", boxShadow: "1px 1px 0 token(colors.brand.ink)" }),
  heroTitle: css({
    mt: "6",
    fontSize: { base: "4xl", md: "6xl", xl: "7xl" },
    fontWeight: "850",
    lineHeight: { base: "1.01", md: "0.94" },
    letterSpacing: "-0.04em",
    maxW: "700px",
    textWrap: "balance",
  }),
  heroCopy: css({ mt: "6", color: "brand.muted", fontSize: { base: "md", md: "xl" }, lineHeight: "1.55", maxW: "60ch" }),
  outcomePath: css({
    mt: "8",
    display: { base: "none", md: "flex" },
    alignItems: "center",
    flexWrap: "wrap",
    gap: "2",
    color: "brand.ink",
    fontSize: { base: "sm", md: "md" },
    fontWeight: "800",
    "& span": { px: "3", py: "2", bg: "brand.panel", borderWidth: "1px", borderColor: "brand.border", borderRadius: "4px" },
    "& svg": { color: "brand.green" },
  }),
  heroFootnotes: css({ mt: { base: "0", lg: "8" }, display: "grid", gap: "2.5", gridColumn: { lg: "1" }, gridRow: { lg: "2" }, alignSelf: "start" }),
  actionStack: css({ display: "grid", gap: "3", maxW: { lg: "540px" }, width: "full", justifySelf: { lg: "end" }, gridColumn: { lg: "2" }, gridRow: { lg: "1 / span 2" } }),
  profileFlow: css({ display: "grid", borderWidth: "1px", borderColor: "brand.ink", bg: "brand.panel", borderRadius: "8px 2px 8px 8px", overflow: "hidden", boxShadow: "8px 8px 0 token(colors.brand.green), 0 22px 60px rgba(21, 24, 39, 0.12)" }),
  intakeHeader: css({ display: "grid", gridTemplateColumns: { base: "1fr", sm: "auto minmax(0, 1fr)" }, alignItems: "start", gap: { base: "3", sm: "4" }, p: { base: "4", md: "5" }, bg: "brand.ink", color: "white" }),
  intakeKicker: css({ mt: "1", px: "2.5", py: "1", bg: "brand.signal", color: "brand.ink", borderRadius: "3px", fontSize: "xs", fontWeight: "850", whiteSpace: "nowrap" }),
  intakeTitle: css({ color: "white", fontSize: { base: "xl", md: "2xl" }, fontWeight: "850", letterSpacing: "tight", lineHeight: "1.08" }),
  intakeCopy: css({ mt: "1.5", color: "#c7ccda", fontSize: "sm", lineHeight: "1.45" }),
  profilePrimaryAction: css({ p: "3", display: "grid", gap: "2", borderTopWidth: "1px", borderColor: "brand.border", bg: "brand.panel", "& button": { width: "full" } }),
  uploadPrompt: css({ color: "brand.muted", fontSize: "xs", textAlign: "center" }),
  intentPanel: css({ borderTopWidth: "1px", borderColor: "brand.border", bg: "#fafbff", "&[open] summary > svg": { transform: "rotate(180deg)" } }),
  intentSummary: css({ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "3", p: { base: "4", md: "5" }, cursor: "pointer", listStyle: "none", _hover: { bg: "brand.sage" }, _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "-2px" }, "&::-webkit-details-marker": { display: "none" }, "& > svg": { color: "brand.green", transition: "transform 160ms ease-out" } }),
  intentBody: css({ px: { base: "4", md: "5" }, pb: { base: "4", md: "5" }, display: "grid", gap: "3" }),
  intentGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", sm: "repeat(2, minmax(0, 1fr))" }, gap: "3" }),
  detailMeter: css({
    mt: "1.5",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "3",
    color: "brand.muted",
    fontSize: "xs",
    lineHeight: "1.4",
    "& strong": {
      flexShrink: "0",
      color: "brand.ink",
      fontVariantNumeric: "tabular-nums",
    },
  }),
  optionalTag: css({ px: "2", py: "0.5", bg: "brand.sageStrong", color: "brand.green", borderRadius: "3px", fontSize: "xs", fontWeight: "800" }),
  exampleFallback: css({ display: "flex", alignItems: "center", flexWrap: "wrap", gap: "1", color: "brand.muted", fontSize: "sm", "& button": { color: "brand.green", px: "2" } }),
  divider: css({ display: "flex", alignItems: "center", gap: "3", color: "brand.muted", fontSize: "sm", _before: { content: '""', h: "1px", bg: "brand.border", flex: "1" }, _after: { content: '""', h: "1px", bg: "brand.border", flex: "1" } }),
  upload: css({ width: "full" }),
  dropzone: css({
    minH: "32",
    display: "grid",
    placeItems: "center",
    textAlign: "center",
    p: "5",
    borderWidth: "0",
    borderStyle: "dashed",
    borderColor: "brand.green",
    borderRadius: "0",
    bg: "brand.sage",
    transition: "common",
    _hover: { bg: "brand.sageStrong" },
    _focusWithin: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" },
  }),
  uploadIcon: css({ boxSize: "11", display: "grid", placeItems: "center", bg: "brand.panel", color: "brand.green", borderWidth: "1px", borderColor: "brand.green", borderRadius: "4px 10px 4px 4px", boxShadow: "2px 2px 0 token(colors.brand.green)" }),
  privacy: css({ display: "flex", alignItems: "start", gap: "2", color: "brand.muted", fontSize: "xs", maxW: "60ch" }),
  previewFrame: css({
    mt: { base: "12", lg: "20" },
    maxW: "1180px",
    mx: "auto",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.ink",
    borderRadius: "10px 2px 10px 10px",
    boxShadow: "8px 8px 0 token(colors.brand.green), 0 18px 46px rgba(21, 24, 39, 0.1)",
    p: { base: "4", md: "6" },
    overflow: "hidden",
  }),
  previewHeader: css({ pb: { base: "5", md: "6" } }),
  previewTitle: css({ maxW: "680px", fontSize: { base: "2xl", md: "3xl" }, lineHeight: "1.08", fontWeight: "850", letterSpacing: "-0.03em", textWrap: "balance" }),
  previewMobileHint: css({ display: { base: "flex", md: "none" }, alignItems: "center", gap: "2", mb: "3", color: "brand.green", fontSize: "xs", fontWeight: "800" }),
  previewScroller: css({ width: "full", overflowX: "auto", overscrollBehaviorX: "contain", pb: "2" }),
  previewBoard: css({ minW: { base: "820px", md: "auto" } }),
  previewAxis: css({ display: "grid", gridTemplateColumns: { base: "170px repeat(3, minmax(0, 1fr))", md: "190px repeat(3, minmax(0, 1fr))" }, gap: "2", mb: "2", color: "brand.ink", fontSize: { base: "sm", md: "md" }, fontWeight: "800", textAlign: "center" }),
  previewRows: css({ display: "grid", gap: "2" }),
  previewRow: css({ display: "grid", gridTemplateColumns: { base: "170px minmax(0, 1fr)", md: "190px minmax(0, 1fr)" }, gap: "2" }),
  previewRowLabel: css({ display: "flex", alignItems: "center", minH: { base: "20", md: "22" }, p: { base: "3", md: "4" }, bg: "brand.ink", color: "white", borderRadius: "4px 1px 1px 4px", "& span": { fontSize: { base: "md", md: "lg" }, lineHeight: "1.2", fontWeight: "850" } }),
  previewRowCells: css({ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "2" }),
  previewCell: css({ minH: { base: "20", md: "22" }, display: "flex", alignItems: "center", borderWidth: "1px", borderColor: "brand.border", borderRadius: "2px", p: { base: "3", md: "4" }, bg: "brand.sage", fontSize: { base: "sm", md: "md" }, fontWeight: "800", lineHeight: "1.3", transition: "common", _hover: { borderColor: "brand.green", transform: "translateY(-1px)" } }),
  previewCellSelected: css({ minH: { base: "20", md: "22" }, display: "flex", alignItems: "center", borderWidth: "1px", borderColor: "brand.ink", borderRadius: "2px", p: { base: "3", md: "4" }, bg: "brand.signal", color: "brand.ink", fontSize: { base: "sm", md: "md" }, fontWeight: "850", lineHeight: "1.3", boxShadow: "3px 3px 0 token(colors.brand.ink)", transform: "translate(-1px, -1px)" }),
  summaryBar: css({
    display: "flex",
    alignItems: { base: "stretch", md: "center" },
    justifyContent: "space-between",
    flexDirection: { base: "column", md: "row" },
    gap: "4",
    p: "4",
    mb: "5",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "6px",
    bg: "brand.panel",
  }),
  workspace: css({ display: "grid", gridTemplateColumns: { base: "minmax(0, 1fr)", xl: "minmax(0, 1fr) 390px" }, gap: "5", alignItems: "start" }),
  workspaceSingle: css({ display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: "5", alignItems: "start" }),
  matrix: css({
    display: { base: "none", lg: "grid" },
    gridTemplateColumns: "190px repeat(3, minmax(0, 1fr))",
    borderTopWidth: "1px",
    borderLeftWidth: "1px",
    borderColor: "brand.border",
    bg: "brand.panel",
    borderRadius: "6px 2px 6px 6px",
    overflow: "hidden",
  }),
  matrixHeader: css({
    minH: "20",
    px: "4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    fontSize: "lg",
    fontWeight: "800",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  rowHeader: css({
    minH: "56",
    p: "4",
    display: "flex",
    alignItems: "center",
    fontSize: "lg",
    fontWeight: "800",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  cell: css({
    minH: "56",
    p: "3",
    display: "flex",
    flexDirection: "column",
    gap: "2",
    bg: "#f7f8ff",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  mobileRows: css({ display: { base: "grid", lg: "none" }, gap: "4" }),
  mobileRow: css({ borderWidth: "1px", borderColor: "brand.border", borderRadius: "l3", bg: "brand.panel", overflow: "hidden" }),
  mobileRowTitle: css({ p: "4", fontSize: "xl", fontWeight: "800", letterSpacing: "tight", borderBottomWidth: "1px", borderColor: "brand.border" }),
  mobileTabs: css({ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", borderBottomWidth: "1px", borderColor: "brand.border" }),
  mobileTab: css({ py: "3", px: "2", textAlign: "center", fontSize: "xs", color: "brand.muted", borderRightWidth: "1px", borderColor: "brand.border", _last: { borderRightWidth: "0" } }),
  card: css({
    width: "full",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "5px 1px 5px 5px",
    p: "3",
    display: "grid",
    gap: "2",
    textAlign: "left",
    cursor: "pointer",
    outline: "none",
    boxShadow: "1px 2px 0 rgba(21, 24, 39, 0.09)",
    transition: "common",
    _hover: {
      borderColor: "brand.green",
      transform: "translateY(-1px)",
      boxShadow: "2px 4px 0 rgba(87, 87, 217, 0.13)",
      "& [data-card-selection]": { opacity: "1", transform: "translateX(0)" },
    },
    _focusVisible: {
      outline: "2px solid token(colors.brand.green)",
      outlineOffset: "2px",
      "& [data-card-selection]": { opacity: "1", transform: "translateX(0)" },
    },
  }),
  cardSelected: css({ borderColor: "brand.ink", bg: "brand.amber", boxShadow: "3px 3px 0 token(colors.brand.ink)" }),
  cardHeader: css({ display: "flex", alignItems: "start", justifyContent: "space-between", gap: "3" }),
  cardHeaderActions: css({ display: "inline-flex", alignItems: "center", justifyContent: "end", gap: "2", flexShrink: "0" }),
  cardTitle: css({ fontWeight: "semibold", minW: "0" }),
  cardSummary: css({ color: "brand.muted", fontSize: "sm", lineHeight: "1.45" }),
  cardSelection: css({
    display: "inline-flex",
    alignItems: "center",
    opacity: "0",
    transform: "translateX(4px)",
    transition: "opacity 140ms ease-out, transform 140ms ease-out",
    color: "brand.ink",
  }),
  cardSelectionSelected: css({ opacity: "1", transform: "translateX(0)" }),
  chip: css({ display: "inline-flex", alignItems: "center", minH: "6", px: "2", borderRadius: "full", fontSize: "xs", fontWeight: "semibold" }),
  chipUse: css({ bg: "brand.sageStrong", color: "brand.green" }),
  chipConfigure: css({ bg: "brand.teal", color: "brand.ink" }),
  chipBuild: css({ bg: "brand.amber", color: "brand.amberInk" }),
  exploreButton: css({ mt: "auto", width: "full", justifyContent: "space-between" }),
  inspector: css({
    position: { base: "fixed", xl: "sticky" },
    inset: { base: "0", xl: "auto" },
    top: { base: "0", xl: "100px" },
    zIndex: { base: "modal", xl: "base" },
    maxH: { base: "100dvh", xl: "calc(100dvh - 120px)" },
    overflowY: "auto",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: { base: "0", xl: "l3" },
    boxShadow: { base: "2xl", xl: "md" },
  }),
  inspectorPlaceholder: css({
    display: { base: "none", xl: "flex" },
    position: "sticky",
    top: "100px",
    minH: "220px",
    alignItems: "center",
    justifyContent: "center",
    p: "8",
    color: "brand.muted",
    textAlign: "center",
    fontSize: "sm",
    lineHeight: "1.6",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "brand.border",
    borderRadius: "6px 2px 6px 6px",
    bg: "rgba(255, 255, 255, 0.5)",
  }),
  inspectorHeader: css({ display: "flex", alignItems: "start", justifyContent: "space-between", gap: "4", p: "5", borderBottomWidth: "1px", borderColor: "brand.border" }),
  inspectorBody: css({ p: "5", display: "grid", gap: "5" }),
  detailSection: css({ display: "grid", gap: "2", pb: "4", borderBottomWidth: "1px", borderColor: "brand.border", _last: { borderBottomWidth: "0", pb: "0" } }),
  warning: css({ p: "4", borderWidth: "1px", borderColor: "brand.amberInk", borderRadius: "l2", bg: "brand.amber", color: "brand.amberInk", display: "flex", alignItems: "start", gap: "3" }),
  profileReview: css({ maxW: "900px", mx: "auto", display: "grid", gap: "6" }),
  factGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "1fr 1fr" }, gap: "4" }),
  panel: css({ bg: "brand.panel", borderWidth: "1px", borderColor: "brand.border", borderRadius: "6px 2px 6px 6px", p: "5", boxShadow: "2px 3px 0 rgba(21, 24, 39, 0.07)" }),
  focusHeader: css({ display: "grid", gap: "3", mb: "6" }),
  breadcrumb: css({ color: "brand.green", fontSize: "sm", display: "flex", flexWrap: "wrap", gap: "2", alignItems: "center" }),
  focusGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))", lg: "repeat(3, minmax(0, 1fr))" }, gap: "4" }),
  choices: css({ display: "flex", flexWrap: "wrap", gap: "2" }),
  choice: css({ px: "4", minH: "10", borderWidth: "1px", borderColor: "brand.border", borderRadius: "l2", bg: "brand.panel", cursor: "pointer", _hover: { borderColor: "brand.green" }, _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" } }),
  choiceActive: css({ borderColor: "brand.green", bg: "brand.sageStrong", color: "brand.green" }),
  notice: css({ p: "3", borderRadius: "l2", bg: "brand.sageStrong", color: "brand.green", fontSize: "sm" }),
  error: css({ p: "3", borderRadius: "l2", bg: "red.subtle.bg", color: "red.subtle.fg", fontSize: "sm" }),
  srOnly: css({ position: "absolute", width: "1px", height: "1px", padding: "0", margin: "-1px", overflow: "hidden", clip: "rect(0,0,0,0)", whiteSpace: "nowrap", border: "0" }),
};
