import { css } from "styled-system/css";

export const styles = {
  app: css({ minH: "100dvh", bg: "brand.canvas", color: "brand.ink" }),
  header: css({
    h: { base: "16", md: "20" },
    px: { base: "4", md: "8" },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
    bg: "brand.panel",
    position: "sticky",
    top: "0",
    zIndex: "sticky",
  }),
  brand: css({ display: "flex", alignItems: "center", gap: "3", minW: "0" }),
  brandMark: css({
    boxSize: "9",
    borderRadius: "l2",
    display: "grid",
    placeItems: "center",
    bg: "brand.green",
    color: "white",
    flexShrink: "0",
  }),
  brandName: css({
    fontFamily: "Georgia, serif",
    fontSize: { base: "lg", md: "2xl" },
    fontWeight: "bold",
    whiteSpace: "nowrap",
  }),
  headerContext: css({
    display: { base: "none", sm: "block" },
    color: "brand.muted",
    borderLeftWidth: "1px",
    borderColor: "brand.border",
    ps: "4",
    ms: "1",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  }),
  page: css({ maxW: "1600px", mx: "auto", px: { base: "4", md: "8" }, py: { base: "6", md: "8" } }),
  landing: css({
    minH: "calc(100dvh - 80px)",
    display: "grid",
    gridTemplateColumns: { base: "1fr", lg: "minmax(0, 0.92fr) minmax(560px, 1.08fr)" },
    gap: { base: "10", lg: "14" },
    alignItems: "center",
    maxW: "1500px",
    mx: "auto",
    px: { base: "5", md: "10" },
    py: { base: "10", lg: "14" },
  }),
  eyebrow: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "2",
    color: "brand.green",
    fontSize: "sm",
    fontWeight: "semibold",
    letterSpacing: "wide",
    textTransform: "uppercase",
  }),
  heroTitle: css({
    mt: "4",
    fontFamily: "Georgia, serif",
    fontSize: { base: "4xl", md: "6xl", xl: "7xl" },
    lineHeight: { base: "1.04", md: "0.98" },
    letterSpacing: "tight",
    maxW: "780px",
  }),
  heroCopy: css({ mt: "5", color: "brand.muted", fontSize: { base: "md", md: "xl" }, lineHeight: "1.7", maxW: "640px" }),
  actionStack: css({ mt: "8", display: "grid", gap: "4", maxW: "560px" }),
  divider: css({ display: "flex", alignItems: "center", gap: "3", color: "brand.muted", fontSize: "sm", _before: { content: '""', h: "1px", bg: "brand.border", flex: "1" }, _after: { content: '""', h: "1px", bg: "brand.border", flex: "1" } }),
  upload: css({ width: "full" }),
  dropzone: css({
    minH: "36",
    display: "grid",
    placeItems: "center",
    textAlign: "center",
    p: "5",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "brand.border",
    borderRadius: "l3",
    bg: "brand.panel",
    transition: "common",
    _hover: { borderColor: "brand.green", bg: "brand.sage" },
    _focusWithin: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" },
  }),
  privacy: css({ display: "flex", alignItems: "start", gap: "2", color: "brand.muted", fontSize: "sm" }),
  previewFrame: css({
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "xl",
    boxShadow: "xl",
    p: { base: "4", md: "6" },
    overflow: "hidden",
  }),
  previewGrid: css({ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "2", mt: "4" }),
  previewCell: css({ minH: "24", borderWidth: "1px", borderColor: "brand.border", borderRadius: "l2", p: "3", bg: "brand.sage", fontSize: "xs" }),
  summaryBar: css({
    display: "flex",
    alignItems: { base: "stretch", md: "center" },
    justifyContent: "space-between",
    flexDirection: { base: "column", md: "row" },
    gap: "4",
    p: "4",
    mb: "5",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "l3",
    bg: "brand.panel",
  }),
  workspace: css({ display: "grid", gridTemplateColumns: { base: "minmax(0, 1fr)", xl: "minmax(0, 1fr) 390px" }, gap: "5", alignItems: "start" }),
  workspaceSingle: css({ display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: "5", alignItems: "start" }),
  matrix: css({
    display: { base: "none", lg: "grid" },
    gridTemplateColumns: "190px repeat(3, minmax(0, 1fr))",
    borderTopWidth: "1px",
    borderLeftWidth: "1px",
    borderColor: "brand.border",
    bg: "brand.panel",
    borderRadius: "l3",
    overflow: "hidden",
  }),
  matrixHeader: css({
    minH: "20",
    px: "4",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    fontFamily: "Georgia, serif",
    fontSize: "lg",
    fontWeight: "bold",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  rowHeader: css({
    minH: "56",
    p: "4",
    display: "flex",
    alignItems: "center",
    fontFamily: "Georgia, serif",
    fontSize: "lg",
    fontWeight: "bold",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  cell: css({
    minH: "56",
    p: "3",
    display: "flex",
    flexDirection: "column",
    gap: "2",
    bg: "brand.sage",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderColor: "brand.border",
  }),
  mobileRows: css({ display: { base: "grid", lg: "none" }, gap: "4" }),
  mobileRow: css({ borderWidth: "1px", borderColor: "brand.border", borderRadius: "l3", bg: "brand.panel", overflow: "hidden" }),
  mobileRowTitle: css({ p: "4", fontFamily: "Georgia, serif", fontSize: "xl", fontWeight: "bold", borderBottomWidth: "1px", borderColor: "brand.border" }),
  mobileTabs: css({ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", borderBottomWidth: "1px", borderColor: "brand.border" }),
  mobileTab: css({ py: "3", px: "2", textAlign: "center", fontSize: "xs", color: "brand.muted", borderRightWidth: "1px", borderColor: "brand.border", _last: { borderRightWidth: "0" } }),
  card: css({
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: "l2",
    p: "3",
    display: "grid",
    gap: "2",
    boxShadow: "xs",
    transition: "common",
    _hover: { borderColor: "brand.green" },
  }),
  cardSelected: css({ borderColor: "brand.green", boxShadow: "0 0 0 1px token(colors.brand.green)" }),
  cardTitleButton: css({ textAlign: "left", fontWeight: "semibold", cursor: "pointer", outline: "none", _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" } }),
  cardSummary: css({ color: "brand.muted", fontSize: "sm", lineHeight: "1.45" }),
  cardActions: css({ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "2" }),
  chip: css({ display: "inline-flex", alignItems: "center", minH: "6", px: "2", borderRadius: "full", fontSize: "xs", fontWeight: "semibold" }),
  chipUse: css({ bg: "brand.sageStrong", color: "brand.green" }),
  chipConfigure: css({ bg: "brand.teal", color: "brand.ink" }),
  chipBuild: css({ bg: "brand.amber", color: "brand.amberInk" }),
  exploreButton: css({ mt: "auto", width: "full", justifyContent: "space-between" }),
  inspector: css({
    position: { base: "fixed", xl: "sticky" },
    inset: { base: "0", xl: "auto" },
    top: { base: "0", xl: "100px" },
    zIndex: { base: "modal", xl: "base" },
    maxH: { base: "100dvh", xl: "calc(100dvh - 120px)" },
    overflowY: "auto",
    bg: "brand.panel",
    borderWidth: "1px",
    borderColor: "brand.border",
    borderRadius: { base: "0", xl: "l3" },
    boxShadow: { base: "2xl", xl: "md" },
  }),
  inspectorHeader: css({ display: "flex", alignItems: "start", justifyContent: "space-between", gap: "4", p: "5", borderBottomWidth: "1px", borderColor: "brand.border" }),
  inspectorBody: css({ p: "5", display: "grid", gap: "5" }),
  detailSection: css({ display: "grid", gap: "2", pb: "4", borderBottomWidth: "1px", borderColor: "brand.border", _last: { borderBottomWidth: "0", pb: "0" } }),
  warning: css({ p: "4", borderWidth: "1px", borderColor: "brand.amberInk", borderRadius: "l2", bg: "brand.amber", color: "brand.amberInk", display: "flex", alignItems: "start", gap: "3" }),
  profileReview: css({ maxW: "900px", mx: "auto", display: "grid", gap: "6" }),
  factGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "1fr 1fr" }, gap: "4" }),
  panel: css({ bg: "brand.panel", borderWidth: "1px", borderColor: "brand.border", borderRadius: "l3", p: "5" }),
  focusHeader: css({ display: "grid", gap: "3", mb: "6" }),
  breadcrumb: css({ color: "brand.green", fontSize: "sm", display: "flex", flexWrap: "wrap", gap: "2", alignItems: "center" }),
  focusGrid: css({ display: "grid", gridTemplateColumns: { base: "1fr", md: "repeat(2, minmax(0, 1fr))", lg: "repeat(3, minmax(0, 1fr))" }, gap: "4" }),
  choices: css({ display: "flex", flexWrap: "wrap", gap: "2" }),
  choice: css({ px: "4", minH: "10", borderWidth: "1px", borderColor: "brand.border", borderRadius: "l2", bg: "brand.panel", cursor: "pointer", _hover: { borderColor: "brand.green" }, _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" } }),
  choiceActive: css({ borderColor: "brand.green", bg: "brand.sageStrong", color: "brand.green" }),
  briefLayout: css({ maxW: "1050px", mx: "auto", display: "grid", gap: "5" }),
  prompt: css({ whiteSpace: "pre-wrap", fontFamily: "mono", fontSize: "sm", lineHeight: "1.6", p: "4", bg: "brand.sage", borderRadius: "l2", borderWidth: "1px", borderColor: "brand.border", maxH: "420px", overflowY: "auto" }),
  downloadLink: css({ display: "inline-flex", alignItems: "center", justifyContent: "center", gap: "2", minH: "10", px: "4", borderWidth: "1px", borderColor: "brand.border", borderRadius: "l2", bg: "brand.panel", fontWeight: "semibold", _hover: { borderColor: "brand.green", bg: "brand.sage" }, _focusVisible: { outline: "2px solid token(colors.brand.green)", outlineOffset: "2px" } }),
  notice: css({ p: "3", borderRadius: "l2", bg: "brand.sageStrong", color: "brand.green", fontSize: "sm" }),
  error: css({ p: "3", borderRadius: "l2", bg: "red.subtle.bg", color: "red.subtle.fg", fontSize: "sm" }),
  srOnly: css({ position: "absolute", width: "1px", height: "1px", padding: "0", margin: "-1px", overflow: "hidden", clip: "rect(0,0,0,0)", whiteSpace: "nowrap", border: "0" }),
};
